export const AVATAR_DATA: { [key: number]: { id: number; url: number } } = [
     { id: 1, url: require("../../../assets/images/dp/1.png") },
     { id: 2, url: require("../../../assets/images/dp/2.png") },
     { id: 3, url: require("../../../assets/images/dp/3.png") },
     { id: 4, url: require("../../../assets/images/dp/4.png") },
     { id: 5, url: require("../../../assets/images/dp/5.png") },
     { id: 6, url: require("../../../assets/images/dp/6.png") },
     { id: 7, url: require("../../../assets/images/dp/7.png") },
     { id: 8, url: require("../../../assets/images/dp/8.png") },
     { id: 9, url: require("../../../assets/images/dp/9.png") },
     { id: 10, url: require("../../../assets/images/dp/10.png") },
     { id: 11, url: require("../../../assets/images/dp/11.png") },
     { id: 12, url: require("../../../assets/images/dp/12.png") },
     { id: 13, url: require("../../../assets/images/dp/13.png") },
     { id: 14, url: require("../../../assets/images/dp/14.png") },
     { id: 15, url: require("../../../assets/images/dp/15.png") },]
