export const AVATAR_MAP: { [key: number]: { id: number; url: number } } = {
  1: { id: 12, url: require("../../../assets/images/dp/1.png") },
  2: { id: 12, url: require("../../../assets/images/dp/2.png") },
  3: { id: 12, url: require("../../../assets/images/dp/3.png") },
  4: { id: 12, url: require("../../../assets/images/dp/4.png") },
  5: { id: 12, url: require("../../../assets/images/dp/5.png") },
  6: { id: 12, url: require("../../../assets/images/dp/6.png") },
  7: { id: 12, url: require("../../../assets/images/dp/7.png") },
  8: { id: 12, url: require("../../../assets/images/dp/8.png") },
  9: { id: 12, url: require("../../../assets/images/dp/9.png") },
  10: { id: 12, url: require("../../../assets/images/dp/10.png") },
  11: { id: 12, url: require("../../../assets/images/dp/11.png") },
  12: { id: 12, url: require("../../../assets/images/dp/12.png") },
  13: { id: 12, url: require("../../../assets/images/dp/13.png") },
  14: { id: 12, url: require("../../../assets/images/dp/14.png") },
  15: { id: 12, url: require("../../../assets/images/dp/15.png") },
};
